{"name": "test_b", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <cases.test_class.TestClass object at 0x000001F22EB1A048>\n\n    @pytest.mark.dependency()\n    def test_b(self):\n        print(\"方法2\")\n>       assert False\nE       assert False\n\ntest_class.py:14: AssertionError"}, "start": 1616999124127, "stop": 1616999124127, "uuid": "a8a2e3e2-4b6b-49fb-b597-4730699b75b1", "historyId": "3666464962ef9b3194d0de8046ac980f", "testCaseId": "9ec1ce2de8879a24acf44e8277658695", "fullName": "cases.test_class.TestClass#test_b", "labels": [{"name": "tag", "value": "dependency"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_class"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "DESKTOP-MI5M7JM"}, {"name": "thread", "value": "13420-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_class"}]}