{"name": "test_b", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <cases.test_class.TestClass object at 0x000001ACA7D64FD0>\n\n    @pytest.mark.dependency()\n    def test_b(self):\n        print(\"方法2\")\n>       assert False\nE       assert False\n\ntest_class.py:14: AssertionError"}, "start": 1617002157290, "stop": 1617002157290, "uuid": "4152821b-a80d-4039-ade7-ff8b135b31e0", "historyId": "3666464962ef9b3194d0de8046ac980f", "testCaseId": "9ec1ce2de8879a24acf44e8277658695", "fullName": "cases.test_class.TestClass#test_b", "labels": [{"name": "tag", "value": "dependency"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_class"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "DESKTOP-MI5M7JM"}, {"name": "thread", "value": "26672-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_class"}]}